version: "3.8"

services:
  dashboard_backend:
    build:
      context: ./dashboard_backend
      dockerfile: Dockerfile
    container_name: dashboard_backend
    ports:
      - "8000:8000"
    env_file:
      - ./dashboard_backend/.env
    volumes:
      - ./dashboard_backend:/app
      - ./dashboard_backend/hotel_dashboard.db:/app/hotel_dashboard.db

  dashboard_frontend:
    build:
      context: ./dashboard_frontend
      dockerfile: Dockerfile
    container_name: dashboard_frontend
    ports:
      - "3000:3000"
    env_file:
      - ./dashboard_frontend/.env
    depends_on:
      - dashboard_backend
    volumes:
      - ./dashboard_frontend:/app
      - /app/node_modules
