version: '3.8'

services:
  dashboard_backend:
    build:
      context: ./dashboard_backend
      dockerfile: Dockerfile
    container_name: dashboard_backend
    ports:
      - "8000:8000"
    env_file:
      - ./dashboard_backend/.env
    volumes:
      - ./dashboard_backend:/app
      - ./dashboard_backend/hotel_dashboard.db:/app/hotel_dashboard.db



